### ISSUE TITLE
Security Password Policy Modification and Creating Users

### ISSUE THREAD

**Issue by dimovelev** [oracle/weblogic-deploy-tooling#1002]
I have the following configuration in the model file:
```
topology:
  SecurityConfiguration:
    Realm:
      myrealm:
        PasswordValidator:
          SystemPasswordValidator:
            SystemPasswordValidator:
              MinNumericOrSpecialCharacters: 0
              MinNumericCharacters: 0
              MinLowercaseCharacters: 0
              MinUppercaseCharacters: 0
              MinNonAlphanumericCharacters: 0
  Security:
    User:
      restclient:
        Name: restclient
        Password: 'restclient'
        Description: 'REST client'
```
When I create the domain, I get a warning that the restclient's password does not have at least one digit and it is not set to the value defined above (restclient). Maybe the order is not correct (first the security configuration and then security) or something else that prevents these two changes to be applied in createDomain.

Tested with WDT 1.9.17 and WebLogic 12.2.1.4
