### ISSUE TITLE
Problem to update JDBC pool for some pools (JDBC driver type)

### ISSUE THREAD

**Issue by enduro99kb** [oracle/weblogic-deploy-tooling#1116]
Hello,
with the latest WDT tool version 2.1.1 together with customer we had found weird behaviour. We run updateDomain.sh script with the model file as below to update JDBC driver to the Active Grid Link (AGL). From 6 datasources, 4 have been changed correctly and 2 are left
[SIT_OSB_JDBC_GridLink.yaml.txt](https://github.com/oracle/weblogic-deploy-tooling/files/8446464/SIT_OSB_JDBC_GridLink.yaml.txt)
 untouched. 

Model file:
```
resources:
  JDBCSystemResource:
    C3_CORE:
        JdbcResource:
            DatasourceType: "AGL"
            JDBCOracleParams:
                        FanEnabled: true
    IMEIDBConnection:
        JdbcResource:
            DatasourceType: "AGL"
            JDBCOracleParams:
                        FanEnabled: true
    'eis/GDM_CORE':
        JdbcResource:
          DatasourceType: "AGL"
          JDBCOracleParams:
            FanEnabled: true
    'eis/GDM_CORE_LEGACY':
        JdbcResource:
           DatasourceType: "AGL"
           JDBCOracleParams:
              FanEnabled: true
    'eis/GDM_CORE_LOG':
          JdbcResource:
            DatasourceType: "AGL"
            JDBCOracleParams:
              FanEnabled: true
    ODSXA:
          JdbcResource:
           DatasourceType: "AGL"
           JDBCOracleParams:
                FanEnabled: true

```

The issue is for eis/GDM_CORE_LEGACY and eis/GDM_CORE_LOG. The change for other pools including the one named very similar eis/GDM_CORE is working fine. As next step we have tried to run the WDT model file with two pools included as below:

```

resources:
  JDBCSystemResource:
    'eis/GDM_CORE_LEGACY':
      JdbcResource:
       DatasourceType: "AGL"
       JDBCOracleParams:
          FanEnabled: true
    'eis/GDM_CORE_LOG':
      JdbcResource:
        DatasourceType: "AGL"
        JDBCOracleParams:
          FanEnabled: true

```

The updateDomain.sh is completing fine, but the pool driver is not changed. The output:

```
####<Apr 7, 2022 2:57:54 PM> <INFO> <WebLogicDeployToolingVersion> <logVersionInfo> <WLSDPLY-01750> <The WebLogic Deploy Tooling updateDomain version is 2.1.1:.d4a1b55:Mar 11, 2022 17:25 UTC>
Please enter the WebLogic administrator password:
####<Apr 7, 2022 2:57:58 PM> <INFO> <ModelContext> <__copy_from_args> <WLSDPLY-01050> <WebLogic version for aliases is 12.2.1.4.0.220105>
####<Apr 7, 2022 2:57:58 PM> <INFO> <filter_helper> <apply_filters> <WLSDPLY-20017> <No filter configuration file /opt/sp/fmw/WDT/weblogic-deploy/lib/model_filters.json>
####<Apr 7, 2022 2:57:58 PM> <INFO> <filter_helper> <apply_filters> <WLSDPLY-20016> <No filters of type update found in filter configuration file /opt/sp/fmw/WDT/weblogic-deploy/lib/model_filters.json>
####<Apr 7, 2022 2:57:58 PM> <INFO> <update> <__update_online> <WLSDPLY-09005> <Connecting to domain at t3://10.2.243.38:7011 with timeout value of 120000 ...>

####<Apr 7, 2022 2:58:04 PM> <INFO> <update> <__update_online> <WLSDPLY-09007> <Connected to domain at t3://10.2.243.38:7011>
####<Apr 7, 2022 2:58:05 PM> <INFO> <LibraryHelper> <install_domain_libraries> <WLSDPLY-12213> <The model did not specify any domain libraries to install>
####<Apr 7, 2022 2:58:05 PM> <INFO> <LibraryHelper> <extract_classpath_libraries> <WLSDPLY-12216> <The archive file was not provided so there are no classpath libraries to extract>
####<Apr 7, 2022 2:58:05 PM> <INFO> <LibraryHelper> <extract_custom_files> <WLSDPLY-12565> <The archive file was not provided so there are no custom files to extract>
####<Apr 7, 2022 2:58:05 PM> <INFO> <LibraryHelper> <install_domain_scripts> <WLSDPLY-12241> <The model did not specify any domain scripts to install>
####<Apr 7, 2022 2:58:05 PM> <INFO> <DatasourceDeployer> <_add_named_elements> <WLSDPLY-09608> <Updating JDBCSystemResource eis/GDM_CORE_LEGACY>
####<Apr 7, 2022 2:58:05 PM> <INFO> <DatasourceDeployer> <_add_model_elements> <WLSDPLY-09604> <Updating JdbcResource for JDBCSystemResource eis/GDM_CORE_LEGACY>
####<Apr 7, 2022 2:58:05 PM> <INFO> <DatasourceDeployer> <_add_model_elements> <WLSDPLY-09603> <Updating JDBCOracleParams for JdbcResource>
####<Apr 7, 2022 2:58:05 PM> <INFO> <DatasourceDeployer> <_add_named_elements> <WLSDPLY-09608> <Updating JDBCSystemResource eis/GDM_CORE_LOG>
####<Apr 7, 2022 2:58:06 PM> <INFO> <DatasourceDeployer> <_add_model_elements> <WLSDPLY-09604> <Updating JdbcResource for JDBCSystemResource eis/GDM_CORE_LOG>
####<Apr 7, 2022 2:58:06 PM> <INFO> <DatasourceDeployer> <_add_model_elements> <WLSDPLY-09603> <Updating JDBCOracleParams for JdbcResource>

Issue Log for updateDomain version 2.1.1 running WebLogic version 12.2.1.4.0.220105 online mode:

Total: WARNING : 0 SEVERE : 0

updateDomain.sh completed successfully (exit code = 0)

```
The JDBC pools configuration for reference:

[jdbc_SIT.zip](https://github.com/oracle/weblogic-deploy-tooling/files/8446494/jdbc_SIT.zip)

I appreciate for any hint how to debug this issue or what could be the reason. I have not found any issue in WDT model_file.

Regards,
Piotr Michalski
Oracle ACS team
