### ISSUE TITLE
ISSUE with update domain

### ISSUE THREAD

**Issue by belfo** [oracle/weblogic-deploy-tooling#1128]
Dear, 

after last issue with update i moved to version 2.2.0 but i still have one issue:

```
Issue Log for updateDomain version 2.2.0 running WebLogic version 12.2.1.4.0.210930 offline mode:
SEVERE Messages:
1. WLSDPLY-09015: updateDomain deployment failed: Unable to create(WSIdentityAsserter, xx.xxx.xx.security.providers.identity.assertion.IdentityAsserter, AuthenticationProvider) in offline mode at location /SecurityConfiguration/base_domain/Realm/myrealm : null
@com.oracle.cie.domain.aspect.AbstractConfigAspect.getAspectClass(AbstractConfigAspect.java:126)
```

The creation of the domain works. but if i do a change (like a new auxilary image) it fail with this error. No change to the SecurityProvider.
The model specify it as:

```
SecurityConfiguration:
  Realm:
    myrealm:
        WSIdentityAsserter:
          xx.xxx.xx.security.providers.identity.assertion.IdentityAsserter:
        DefaultAuthenticator:
          DefaultAuthenticator:
            ControlFlag: OPTIONAL
        DefaultIdentityAsserter:
          DefaultIdentityAsserter:
```
