### ISSUE TITLE
Update RemoteAnonymousRmiiiopEnabled and RemoteAnonymousRmit3Enabled from true to false is not working with WDT

### ISSUE THREAD

**Issue by Michalski-Piotr** [oracle/weblogic-deploy-tooling#1189]
After installing recent WLS PSU for 12.2.1.4 there is security warning to disable RemoteAnonymousRMIT3Enabled and RemoteAnonymousRMIIIOPEnabled, reference:

Oracle Support Document 2795381.1 (Setting the RemoteAnonymousRMIT3Enabled and RemoteAnonymousRMIIIOPEnabled Attributes to False) can be found at: https://mosemp.us.oracle.com/epmos/faces/DocumentDisplay?id=2795381.1

I'm trying to change it with WDT 2.3.2 with the following model file:

```
topology:
    SecurityConfiguration:
         RemoteAnonymousRmiiiopEnabled: false
         RemoteAnonymousRmit3Enabled: false
```

updateDomain.sh (online mode) is completing without any issue, but the problem is that both properties are still set to "true"

change:

```
wlst> cd ('/SecurityConfiguration/o2c-domain')

ls ()

-r--   RemoteAnonymousRMIIIOPEnabled                true
-r--   RemoteAnonymousRMIT3Enabled                  true
```

I changed these two properties to false with WLST (https://docs.oracle.com/en/middleware/fusion-middleware/weblogic-server/12.2.1.4/lockd/secure.html#GUID-4148D1BE-2D54-4DA5-8E94-A35D48DCEF1D
)

```
edit()
startEdit()
cd("SecurityConfiguration/o2c-domain")
ls ()
cmo.setRemoteAnonymousRMIIIOPEnabled(false)
cmo.setRemoteAnonymousRMIT3Enabled(false)
activate()
```
In that case changes is fine.

And now when I'm changing from false to true with WDT it is working fine.

model file:

```
topology:
    SecurityConfiguration:
         RemoteAnonymousRmiiiopEnabled: true
         RemoteAnonymousRmit3Enabled: true
```
The question is why change from true to false is not working with WDT. Could you help me to understand and fix this issue, please?

Is it related with https://github.com/oracle/weblogic-deploy-tooling/pull/1122 fix perhaps?

Regards,
Piotr
