### ISSUE TITLE
SingleSignOn name

### ISSUE THREAD

**Issue by antonionappi88** [oracle/weblogic-deploy-tooling#13]
Hello,
I'm trying to configure the single sign on for the server

I tried in two different way: 

```yaml
SingleSignOnServices:
       AdminServer:
            Name: AdminServer
            WantArtifactRequestsSigned: true
```

or 

```yaml
SingleSignOnServices:
     Name: AdminServer
     WantArtifactRequestsSigned: true
```

but the result is always the same: 

```xml
  <single-sign-on-services>
    <name>NO_NAME_0</name>
  </single-sign-on-services>

```
