### ISSUE TITLE
validation process

### ISSUE THREAD

**Issue by antonionappi88** [oracle/weblogic-deploy-tooling#14]
Hello,
I tried to add a random string to the AdminServer configuration like this (last line): 

```yaml
 AdminServer:
            TunnelingEnabled: true
            ListenAddress: wlsadmin
            ListenPort: 8001
            WeblogicPluginEnabled: true
            KeyStores: CustomIdentityAndCustomTrust
            CustomIdentityKeyStoreFileName: "/ORA/dbs01/oracle/product/Middleware/user_projects/domains/base_domain/security/ITDBIdentity.jks"
            CustomIdentityKeyStoreType: jks
            CustomIdentityKeyStorePassPhraseEncrypted: linux
            CustomTrustKeyStoreFileName: "/ORA/dbs01/oracle/product/Middleware/user_projects/domains/base_domain/security/ITDBTrust.jks "
            CustomTrustKeyStoreType: jks
            CustomTrustKeyStorePassPhraseEncrypted: linux
            Prova:
                ciao: true
```

when I run the validateModel.sh, it complains but returns exit code 0.

```bash
Validation Area: topology Section
-----------------------------------------------

  Errors: 1
    Message: Prova is not one of the folder names allowed in model location topology:/Server/AdminServer

validateModel.sh completed successfully (exit code = 0)
```

Probably in order to automate the process would be better to have an exit code with 1 and a different message at the end.
