### ISSUE TITLE
Support for policy

### ISSUE THREAD

**Issue by gregoan** [oracle/weblogic-deploy-tooling#1496]
Hello,

Some of our instances are really sensitives and customers added security on top of JMS queues.
Today with WDT there is no capability to export policy but neither create policy.

This is really problematic for us to enforce our customers to migrate because thy will have something less secured than what they can have with legacy infrastructure.

Will it be possible to have the capability to create policies ?

Regards.

**Comment by robertpatrick** [comment]
@gregoan Can you give me an example or two of what the policies you need to create look like?  We are discussing this and may be able to do something but the input needed is complex so I am trying to find a way to model the input in a more natural way.

**Comment by gregoan** [comment]
Hello,

Here is example based on our old framework implementation :

############################################################
#  DS and JNDI Security
##################################################################
security.policies.items = 2

security.policies.0.mode = CREATE
security.policies.0.resource = type=<jdbc>, application=, module=,
resourceType=ConnectionPool, resource=Sysper2JDBCTxDataSource
security.policies.0.realm = myrealm
security.policies.0.authorizer = XACMLAuthorizer
security.policies.0.expression =
Rol(Deployer,Admin,Monitor,Operator)|Grp(sysper2_ecas_user_group,sysper2_group)

security.policies.1.mode = UPDATE
security.policies.1.resource = type=<jndi>
security.policies.1.realm = myrealm
security.policies.1.authorizer = XACMLAuthorizer
security.policies.1.expression =
Rol(Deployer,Admin,Monitor,Operator)|Grp(sysper2_ecas_user_group,sysper2_group)
security.policies.1.expression.update.mode = REPLACE

I can also provide something related to JMS if you need.

Regards.

Le sam. 28 oct. 2023 à 20:10, Robert Patrick ***@***.***> a
écrit :

**Comment by gregoan** [comment]
Hello,

Here is example based on our old framework implementation :

```
############################################################
#  DS and JNDI Security
##################################################################
security.policies.items = 2

security.policies.0.mode = CREATE
security.policies.0.resource = type=<jdbc>, application=, module=,
resourceType=ConnectionPool, resource=Sysper2JDBCTxDataSource
security.policies.0.realm = myrealm
security.policies.0.authorizer = XACMLAuthorizer
security.policies.0.expression =
Rol(Deployer,Admin,Monitor,Operator)|Grp(sysper2_ecas_user_group,sysper2_group)

security.policies.1.mode = UPDATE
security.policies.1.resource = type=<jndi>
security.policies.1.realm = myrealm
security.policies.1.authorizer = XACMLAuthorizer
security.policies.1.expression =
Rol(Deployer,Admin,Monitor,Operator)|Grp(sysper2_ecas_user_group,sysper2_group)
security.policies.1.expression.update.mode = REPLACE
```

I can also provide something related to JMS if you need.

Regards.

**Comment by robertpatrick** [comment]
Fix for this issue merged into the develop-4.0 branch. WDT 4.0 is on track for release next month.

**Comment by gregoan** [comment]
Thanks for all.

Le lun. 8 janv. 2024 à 21:12, Robert Patrick ***@***.***> a
écrit :

**Comment by tdferreira** [comment]
Hello, is there defined any date for WDT 4.0 to be released?

**Comment by robertpatrick** [comment]
WDT 4.0.0 released so closing as resolved.

**Comment by tdferreira** [comment]
Just to clarify, the Discover Domain Tool in WDT 4.0.0 does not export the existing policies, right?

**Comment by robertpatrick** [comment]
@tdferreira Much like other security data fields (users, groups, credential mappings, etc.), WDT does not support discovery of these policies.

**Comment by tdferreira** [comment]
I have found an issue related to this.
When using, for example, the oracle weblogic 12 dev docker image "container-registry.oracle.com/middleware/weblogic:12.2.1.4-dev-ol8", it already has a JNDI Policy with Resource ID "type=<jndi>" defined by default.
Basically, this exists already in the Root Level:

```
    WLSPolicies:
        JNDI:
            ResourceID: 'type=<jndi>'
            Policy: 'Grp(everyone)'
```

If I try to create my domain with this:
```
    WLSPolicies:
        MyJNDIPolicy:
            ResourceID: 'type=<jndi>'
            Policy: 'Rol(Deployer,Admin,Monitor,Operator)|Grp(my_user_group)'
```

I get the following error:
```
19.58 SEVERE Messages:
19.58 
19.58         1. WLSDPLY-12601: The policy MyJNDIPolicy is invalid because the ResourceID attribute value type=<jndi> matches built-in policy ResourceID field value with a policy of Grp(everyone)
19.58         2. WLSDPLY-20001: createDomain did not complete the operation because validation failed
19.58         3. WLSDPLY-12409: createDomain failed to create the domain: createDomain did not complete the operation because validation failed
19.58 
19.58 Total:   SEVERE :    3  WARNING :    0
```

It would be good if we could have an extra parameter that would tell what to do if there's an existing policy.
Something like:
```
    WLSPolicies:
        MyJNDIPolicy:
            ResourceID: 'type=<jndi>'
            Policy: 'Rol(Deployer,Admin,Monitor,Operator)|Grp(my_user_group)'
            **ReplaceIfExists: true|false**
```

Also, if we have multiple realms, how can we specify for which realm the policy is?
Couldn't we also have a parameter for that?
Something like:
```
    WLSPolicies:
        MyJNDIPolicy:
            ResourceID: 'type=<jndi>'
            Policy: 'Rol(Deployer,Admin,Monitor,Operator)|Grp(my_user_group)'
            Realm: myrealm
            ReplaceIfExists: true|false
```
