### ISSUE TITLE
JRF Domain - How to connect RCU to SQL server database

### ISSUE THREAD

**Issue by sebfortier2288** [oracle/weblogic-deploy-tooling#1534]
Hello,
I would like to know if it is possible to configure the RCU to connect to a SQL server database and if it is, how can we do it.
We are able to do it when manually executing the RCU in interactive mode (with the UI) on RHEL servers. I didn't find a way to do the same thing with WDT models.

So far I have this configuration:
```
domainInfo:
  RCUDbInfo:
    rcu_prefix: '@@SECRET:test-rcu-access:rcu_prefix@@'
    rcu_schema_password: '@@SECRET:test-rcu-access:rcu_schema_password@@'
    rcu_db_conn_string: '@@SECRET:test-rcu-access:rcu_db_conn_string@@'
    rcu_admin_user: '@@SECRET:test-rcu-access:rcu_db_user@@'
    rcu_admin_password: '@@SECRET:test-rcu-access:rcu_db_pwd@@'
```

And I added a JDBCSystemResource for the sqljdbc driver (not sure if it is the right way to do it though...):
```
resources:
  JDBCSystemResource:
    jdbc/sqljdbc:
      JdbcResource:
        JDBCDataSourceParams:
          JNDIName: [
            jdbc/sqljdbc
          ]
          GlobalTransactionsProtocol: None
        JDBCDriverParams:
          DriverName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          URL: @@SECRET:test-rcu-access:rcu_db_conn_string@@'
          PasswordEncrypted: @@SECRET:test-rcu-access:rcu_db_pwd@@'
          Properties:
            user:
              Value: @@SECRET:test-rcu-access:rcu_db_user@@'
        JDBCConnectionPoolParams:
          TestTableName: SQL SELECT 1
          TestConnectionsOnReserve: true
```

With this configuration, I see in the log that it is trying to connect to an Oracle database:

`<Executing rcu: [cmd:[/usr/bin/sh, -c, /u01/oracle/oracle_common/bin/rcu -silent -dropRepository -databaseType ORACLE -connectString "jdbc:sqlserver://my.mssql.host:1433;databaseName=my_db" -dbUser db_user -dbRole SYSDBA -schemaPrefix my_schema -component MDS -component IAU -component IAU_VIEWER -component IAU_APPEND -component OPSS -component STB -component WLS -f]]>`

I saw in this documentation that the rcu cmdline param "-databaseType" supports the SQLSERVER value: [RCU](https://docs.oracle.com/middleware/1221/core/RCUUG/GUID-0D3A2959-7CC8-4001-997E-718ADF04C5F2.htm#RCUUG248)

I tried adding this to the RCUDbInfo object in the model, but that didn't work:
`databaseType: 'SQLSERVER'`
In the logs, it say that I'm trying to use ATP database and that I'm missing tnsnames, etc...

Thank you for your help!
