### ISSUE TITLE
Improve support for policies

### ISSUE THREAD

**Issue by tdferreira** [oracle/weblogic-deploy-tooling#1545]
Hello,

As pointed out in https://github.com/oracle/weblogic-deploy-tooling/issues/1496#issuecomment-2040329919, I'm opening this issue to request improvement in the support for policies within WDT.

When using, for example, the oracle weblogic 12 dev docker image: 
`container-registry.oracle.com/middleware/weblogic:12.2.1.4-dev-ol8`
it already has a JNDI Policy with Resource ID `type=<jndi>` defined by default.
Basically, this exists already in the Root Level:

```
    WLSPolicies:
        JNDI:
            ResourceID: 'type=<jndi>'
            Policy: 'Grp(everyone)'
```

If I try to create my domain with this:
```
    WLSPolicies:
        MyJNDIPolicy:
            ResourceID: 'type=<jndi>'
            Policy: 'Rol(Deployer,Admin,Monitor,Operator)|Grp(my_user_group)'
```

I get the following error:
```
19.58 SEVERE Messages:
19.58 
19.58         1. WLSDPLY-12601: The policy MyJNDIPolicy is invalid because the ResourceID attribute value type=<jndi> matches built-in policy ResourceID field value with a policy of Grp(everyone)
19.58         2. WLSDPLY-20001: createDomain did not complete the operation because validation failed
19.58         3. WLSDPLY-12409: createDomain failed to create the domain: createDomain did not complete the operation because validation failed
19.58 
19.58 Total:   SEVERE :    3  WARNING :    0
```

It would be good if we could have an extra parameter that would tell what to do if there's an existing policy.
Something like:
```
    WLSPolicies:
        MyJNDIPolicy:
            ResourceID: 'type=<jndi>'
            Policy: 'Rol(Deployer,Admin,Monitor,Operator)|Grp(my_user_group)'
            **ReplaceIfExists: true|false**
```

Also, if we have multiple realms, how can we specify for which realm the policy is?
it would be good if we could also have a parameter for that. Something like:
```
    WLSPolicies:
        MyJNDIPolicy:
            ResourceID: 'type=<jndi>'
            Policy: 'Rol(Deployer,Admin,Monitor,Operator)|Grp(my_user_group)'
            Realm: myrealm
            ReplaceIfExists: true|false
```

Would it also be possible that you could enhance WDT in order to use something like the [WebLogic Remote Console extension](https://oracle.github.io/weblogic-remote-console/setup/console/#ext) to make WDT able to use the Discovery Domain Tool to extract the users, groups, policies, credential mappings, etc?

Can you please consider these improvements?
Thanks
