### ISSUE TITLE
SSL listen port

### ISSUE THREAD

**Issue by antonionappi88** [oracle/weblogic-deploy-tooling#20]
Hello,

I'm having a problem configuring the SSL port for AdminServer (also Managed).

I have something like : 

```yaml
 
 TunnelingEnabled: true
 ListenAddress: wlsadmin
 ListenPort: 8001
 SSL:
     Enabled: true
     ListennnnnnPort: 7002
     ServerPrivateKeyAlias: myalias
     ServerPrivateKeyPassPhraseEncrypted: mypassword
     HostnameVerifier: "weblogic.security.utils.SSLWLSWildcardHostnameVerifier"
```

Both the validateModel.sh and the createDomain.sh scripts ignore the uncorrect attribute `ListennnnnPort`.
This happen just with the SSL configuration, infact if I do the same for the http listen port, the scripts complain about the typo.

When I introduce the typo, in the config.xml file under the ssl section there is not listen-port tag.

I'm using the weblogic-deploy 0.7 release. #21
