### ISSUE TITLE
JNDI Name in Data Source seems to wrong

### ISSUE THREAD

**Issue by chiroito** [oracle/weblogic-deploy-tooling#255]
I use weblogic-deploy-tooling ver.0.18 and WebLogic Server 12.2.1.3.0.

I created a data source using datasource.yml. However, JNDI Name in WLS Admin Console is as follows. This behavior is correct? I would like to set "jdbc/generic1" to JNDI Name.

JNDI Name in WebLogic Admin Console
```
MyDataSource
jdbc/generic1
```

datasource.yml
```
resources:
    JDBCSystemResource:
        MyDataSource:
            Target: '@@PROP:myjcs.cluster1.name@@'
            JdbcResource:        
                JDBCDataSourceParams:
                    JNDIName: jdbc/generic1
                JDBCDriverParams:
                    DriverName: oracle.jdbc.OracleDriver
                    URL: 'jdbc:oracle:thin:@//@@PROP:dbcs1.url@@'
                    PasswordEncrypted: '@@PROP:dbcs1.password@@'
                    Properties:
                        user:
                            Value: '@@PROP:dbcs1.user@@'
                        oracle.net.CONNECT_TIMEOUT:
                            Value: 5000
                JDBCConnectionPoolParams:
                    MaxCapacity: 50
```
