### ISSUE TITLE
security_configuration issue

### ISSUE THREAD

**Issue by MarinaLevin** [oracle/weblogic-deploy-tooling#280]
When running the updateDomain utility we are failing with te following error:
####<Mar 14, 2019 3:09:39 PM> <INFO> <Creator> <_create_mbean> <WLSDPLY-20013> <Updating SecurityConfiguration>
####<Mar 14, 2019 3:09:39 PM> <SEVERE> <update> <main> <WLSDPLY-09015> <updateDomain deployment failed: Server wl_default_realm not found in domain or resource group>
We have if len(security_configuration_nodes) > 0, and in order to fix the problem it seems the following should be done in  security_provider_creator.py  
In create_security_configuration method to pass “config_location” instead of “location”:
        if len(security_configuration_nodes) > 0:
            #self._create_mbean(SECURITY_CONFIGURATION, security_configuration_nodes, location, log_created=True)
            self._create_mbean(SECURITY_CONFIGURATION, security_configuration_nodes, config_location, log_created=True)
            print 'security_configuration_nodes>0'

**Comment by rakillen** [comment]
Hi, I believe the existing code is correct - _create_mbean() should be creating the SecurityConfiguration MBean in the root location, not the appended location. The error message is confusing, since it appears to be looking for a Server MBean named wl_default_realm. I suspect this is a problem with the model structure, possibly from a section prior to the SecurityConfiguration. Can you attach your model so we can test with it?

The security section of my test model looks like: 
```
    SecurityConfiguration:
        Realm:
            wl_default_realm:
                AuthenticationProvider:
                    DefaultAuthenticator:
                        DefaultAuthenticator:
                            ControlFlag: "OPTIONAL"
```
