### ISSUE TITLE
Unable to set attributes on AdminConsoleMBean

### ISSUE THREAD

**Issue by 53d117460ec63d70** [oracle/weblogic-deploy-tooling#298]
Doesn't look like we can set attributes on the AdminConsoleMBean?:
```yaml
topology:
    Name: mydomain
    AdminConsole:
        CookieName: mydomaincookie
```
The model fails validation:
```
<WLSDPLY-05026> <AdminConsole is not one of the folder names allowed in model location topology:/>'
```
Also, these values aren't added to the model during domain discovery.
