### ISSUE TITLE
Domain creation incorrectly handles JDWP start args

### ISSUE THREAD

**Issue by 53d117460ec63d70** [oracle/weblogic-deploy-tooling#300]
Extract from my model:
```yaml
topology:
    Server:
        admin:
            ServerStart:
                Arguments: '-Xrunjdwp:transport=dt_socket,address=8888,server=y,suspend=y'
```
This produces in the config.xml:
```xml
<arguments>-Xrunjdwp</arguments>
```
Tested on WLS10.3.6.
