### ISSUE TITLE
create domain ignoring NumberOfFilesLimited on WebServerLog

### ISSUE THREAD

**Issue by 53d117460ec63d70** [oracle/weblogic-deploy-tooling#303]
model extract:
```yaml
topology:
    Server:
        myserver:
            WebServer:
                WebServerLog:
                    FileCount: 5
                    BufferSizeKb: 0
                    NumberOfFilesLimited: true
```
produces config.xml extract:

```xml
      <web-server-log>
        <name>myserver</name>
        <file-count>5</file-count>
        <buffer-size-kb>0</buffer-size-kb>
      </web-server-log>
```
Attribute is confirmed as being ```false``` in WLST:
```python
wls:/mydomain/serverConfig> get('Servers/myserver/WebServer/myserver/WebServerLog/myserver/NumberOfFilesLimited')
0
```
Tested in WLS10.3.6. Setting the attribute works on wls12.1.3
