### ISSUE TITLE
create domain issue with RotateLogOnStartup

### ISSUE THREAD

**Issue by 53d117460ec63d70** [oracle/weblogic-deploy-tooling#304]
model extract:
```yaml
topology:
    Server:
        myserver:
            Log:
                RotateLogOnStartup: true
```
This doesn't get set in wls10.3.6 or wls12.1.3.

There seems to be a discrepancy between WLST online::
```python
wls:/mydomain/serverConfig> get('Servers/myserver/Log/myserver/RotateLogOnStartup')
0
```
And WLST offline:
```
wls:/offline/mydomain/Server/myserver/Log/myserver> x=get('RotateLogOnStartup');print x
1
```
