### ISSUE TITLE
WLS10.3.6 discovered SAFAgent config skipped during create

### ISSUE THREAD

**Issue by 53d117460ec63d70** [oracle/weblogic-deploy-tooling#316]
Discover generates the following SAFAgent extract in the model:
```yaml
resources:
    SAFAgent:
        MyAgent1:
            Store: MyStore1
            ServiceType: 'Sending-only'
            JmssafMessageLogFile:
                FileName: logs/safagents/MyAgent1/jms/jms.messages.log
                FileMinSize: 5000
                RotateLogOnStartup: false
                NumberOfFilesLimited: false
```
However, we see the following warning when the generated model is used to create:
```
<WLSDPLY-05027> <Model folder resources:/SAFAgent/MyAgent1/JmssafMessageLogFile is not valid for WLS version 10.3.6.0, folder was skipped>
```
