### ISSUE TITLE
NodeManager always listen on SecureConnection

### ISSUE THREAD

**Issue by dbechtel89** [oracle/weblogic-deploy-tooling#322]
I configure my machines with a nodemanager with NMType "Plain". It configures the machines correct with NMType "Plain", but the SecureListener property in nodemanager.properties file is set to true.

**Comment by jshum2479** [comment]
There is a confusion in the setup, the nodemanager section and NMType within the model is defining what mode should the domain used to communicate with the actual node manager,  it doesn't define what mode the actual nodemanager is listening with.  

You can define a NMProperties section under topology to change the settings of the nodemanager properties. For example,

```yaml
topology:
    Name: simple_domain_jrf
    NMProperties:
        SecureListener : false
```
