### ISSUE TITLE
WLS10.3.6 - Unable to set attributes on WebAppContainer MBean

### ISSUE THREAD

**Issue by 53d117460ec63d70** [oracle/weblogic-deploy-tooling#324]
Model extract:
```yaml
topology:
    WebAppContainer:
        XPoweredByHeaderLevel: NONE
```
Create domain fails with the message:
```
<WLSDPLY-05026> <WebAppContainer is not one of the folder names allowed in model location topology:/>'
```
