### ISSUE TITLE
MailSession error when updating WLS10.3.6 domain

### ISSUE THREAD

**Issue by 53d117460ec63d70** [oracle/weblogic-deploy-tooling#328]
I am testing the workaround for https://github.com/oracle/weblogic-deploy-tooling/issues/303#issuecomment-476768240 by updating a WLS10.3.6 domain using WDT 0.21 in online mode. However the update is failing with the following error:
```
Issue Log for updateDomain version 0.21 running weblogic version 10.3.6.0 online mode:

SEVERE Messages:

        1. WLSDPLY-09015: updateDomain deployment failed: Failed to get existing WLST value for model attribute Properties at location resources:/MailSession/MyMailSession because the attribute map did not contain the key Properties

Total:       WARNING :     0    SEVERE :     1

```
The domain was created without error using WDT 0.21. The model contains the following `MailSession` configuration:
```yaml
    MailSession:
        MyMailSession:
            Properties:
                mail.from: 'rob@rob.co.uk'
                mail.transport.protocol: smtp
                mail.smtp.host: mysmtphost
            JNDIName: MyMailSession
            Target: 'blah,hmm,grr'
```
The generated config.xml has the following block:
```xml
  <mail-session>
    <name>MyMailSession</name>
    <target>blah,hmm,grr</target>
    <jndi-name>MyMailSession</jndi-name>
    <properties>mail.from=rob@rob.co.uk;mail.transport.protocol=smtp;mail.smtp.host=mysmtphost</properties>
  </mail-session>
```
The update isn't changing any of the `MailSession` confguration and uses the same model as the create.
