### ISSUE TITLE
WLS10.3.6/WDT0.21 - error setting DefaultRealm

### ISSUE THREAD

**Issue by 53d117460ec63d70** [oracle/weblogic-deploy-tooling#330]
Extract from my model following domain discovery:
```yaml
        DefaultRealm: robrealm
        Realm:
            robrealm:
                Adjudicator:
                    DefaultAdjudicator:
                        DefaultAdjudicator:
                AuthenticationProvider:
                    DefaultAuthenticator:
                        DefaultAuthenticator:
                    DefaultIdentityAsserter:
                        DefaultIdentityAsserter:
                            ActiveType: [ AuthenticatedUser ]
                Authorizer:
                    XACMLAuthorizer:
                        XACMLAuthorizer:
                            PolicyDeploymentEnabled: true
                CertPathProvider:
                    WebLogicCertPathProvider:
                        WebLogicCertPathProvider:
                CredentialMapper:
                    DefaultCredentialMapper:
                        DefaultCredentialMapper:
                RoleMapper:
                    XACMLRoleMapper:
                        XACMLRoleMapper:
```
Causes the following error during domain create:
```
WLSDPLY-12409: createDomain failed to create the domain: Failed to set attribute DefaultRealm to value Proxy for robrealm: Name=robrealm, Type=SecurityConfiguration!Realm: wlst.set(DefaultRealm, Proxy for robrealm: Name=robrealm, Type=SecurityConfiguration!Realm) in offline mode failed : java.lang.IllegalArgumentException: Param type com.sun.proxy.$Proxy16 not supported
```
