### ISSUE TITLE
Schema Password can not be null

### ISSUE THREAD

**Issue by 53d117460ec63d70** [oracle/weblogic-deploy-tooling#384]
I'm getting the following error when creating an OID 12.2.1.3 domain:
```
Schema Password can not be null. Schema Password for component ROB_WLS is null.

ERROR - RCU-6091 Component validation failed.
CAUSE - RCU-6091 One or more component specific validation failed.
ACTION - RCU-6091 Check log for more details and fix the validation error.
```
Model:
```
domainInfo:
    AdminUserName: weblogic
    AdminPassword: welcome1
    ServerStartMode: prod
    RCUDbInfo:
        rcu_prefix : ROB
        rcu_db_conn_string: 'dbhost:1521/MYDB'
        rcu_variables: 'WORK_REPOSITORY_TYPE=D,WORK_REPO_NAME=WORKREP,ENCRYPTION_ALGORITHM=AES-128'
        rcu_schema_password: 'welcome1'
        rcu_admin_password: 'welcome1'
```
Typedef:
```
{
    "copyright": "Copyright (c) 2017, 2018, Oracle and/or its affiliates. All rights reserved.",
    "license": "The Universal Permissive License (UPL), Version 1.0",
    "name": "WLS",
    "description": "WLS type domain definitions",
    "versions": {
        "10.3.6": "WLS_11G",
        "12.1.1": "WLS_11G",
        "12.1.2": "WLS_12CR1",
        "12.1.3": "WLS_12CR1",
        "12.2.1": "WLS_12CR2",
        "19.1":   "WLS_19CR1"
    },
    "definitions": {
        "WLS_11G": {
            "baseTemplate": "@@WL_HOME@@/common/templates/domains/wls.jar",
            "extensionTemplates": [ ],
            "customExtensionTemplates": [ ],
            "serverGroupsToTarget": [ ],
            "rcuSchemas": [ ]
        },
        "WLS_12CR1": {
            "baseTemplate": "@@WL_HOME@@/common/templates/wls/wls.jar",
            "extensionTemplates": [ ],
            "customExtensionTemplates": [ ],
            "serverGroupsToTarget": [ ],
            "rcuSchemas": [ ]
        },
        "WLS_12CR2": {
            "baseTemplate": "Basic WebLogic Server Domain",
            "extensionTemplates": [
                "Oracle Data Integrator - Agent"
            ],
            "customExtensionTemplates": [ ],
            "serverGroupsToTarget": [ ],
            "rcuSchemas": [ "STB","OPSS","ODI","IAU","IAU_APPEND","IAU_VIEWER","WLS" ]
        },
        "WLS_19CR1": {
            "baseTemplate": "Basic WebLogic Server Domain",
            "extensionTemplates": [ ],
            "customExtensionTemplates": [ ],
            "serverGroupsToTarget": [ ],
            "rcuSchemas": [ ]
        }
    }
}
```
I am able to work around this issue by adding a conditional to `@@ORACLE_HOME@@/oracle_common/bin/rcu` which injects the `-useSamePasswordForAllSchemaUsers true` argument when `-createRepository` is passed:
```
[[ $ARGUMENTS == *create* ]] && ARGUMENTS="$ARGUMENTS -useSamePasswordForAllSchemaUsers true"
```
