### ISSUE TITLE
custom name for deployed application

### ISSUE THREAD

**Issue by cchaplin** [oracle/weblogic-deploy-tooling#434]
I have created a domain model file with following content

```
appDeployments:
    Application:
        "payments-cardpayment":
            SourcePath: "wlsdeploy/applications/payments-cardpayment-ear-137045-20190807.103010-1.ear"
			ApplicationName: 'payments-cardpayment-137045'
            ModuleType: 'ear'
            Target: 'managed1,managed2'
```

and when i try to deploy this application using deployApps.sh, the tool is not taking the ApplicationName parameter as defined in the model file. 
It computes application name as "payments-cardpayment-ear-137045-SNAPSHOT" and below is the content of my MANIFEST file

> Manifest-Version: 1.0
> Archiver-Version: Plexus Archiver
> Created-By: Apache Maven
> Built-By: 006w5vf
> Build-Jdk: 1.7.0_171
> Specification-Title: payments-cardpayment-ear
> Specification-Version: 137045-SNAPSHOT
> Implementation-Title: payments-cardpayment-ear
> Implementation-Version: 137045-SNAPSHOT
> Extension-Name: payments-cardpayment-ear-137045-SNAPSHOT
> Version: 137045
> artifact-name: payments-cardpayment-ear
> artifact-version: payments-cardpayment-ear

I would like the name of the application (as seen in weblogic console) to be as i specified in ApplicationName paramter of the model. Is it a bug?
