### ISSUE TITLE
Does WDT support role mappings?

### ISSUE THREAD

**Issue by gasgithub** [oracle/weblogic-deploy-tooling#482]
I have domain with LDAP groups mapped to roles. I did domain discovery, but role mappings are not there. Any way or plan to support that in the tool? Any way I could manually inject that in the model?

Regards
Greg

**Comment by ddsharpe** [comment]
Have you seen the documentation at https://github.com/oracle/weblogic-deploy-tooling/blob/master/site/security_users_groups_roles.md?
The way that WebLogic protects the security realm information makes it difficult and sometimes impossible to get complete data through discovery.  Please read through that document and let me know what you think we should expand on to make it easier to do.

**Comment by gasgithub** [comment]
Hi,

Thnaks it worked.

I've checked that link, and tried to add to the mydomain.yaml section like:

```
domainInfo:
    WLSRoles:
      Admin:
        UpdateMode: append    
        Expression: "?weblogic.entitlement.rules.AdministrativeGroup(wlsadmins)"
```
first I got error:
`####<Nov 30, 2019 8:41:09 PM> <SEVERE> <ValidationResults> <log_results> <WLSDPLY-05029> <WLSRoles is not one of the attribute names allowed in model location domainInfo:/>`
Am I doing something wrong? I wanted to modify Admin global role with the wlsamins group.

But after updating wdt to the latest version it built and ran successfully.
