### ISSUE TITLE
How to set user attribute from domain model?

### ISSUE THREAD

**Issue by ciancu** [oracle/weblogic-deploy-tooling#492]
I have an user model which creates some groups and users:
```
    Security:
        Group:
            USAR_ADMIN:
                Description: The USAR Admin group
            USAR_EF_USER:
                Description: The USAR User group
        User:
            itar_admin:
                Password: welcome1
                GroupMemberOf: [ USAR_ADMIN ]
            itar_user:
                Password: welcome1
                GroupMemberOf: [ USAR_EF_USER ]
```
I will need to set the user email attribute, WLST that can achive this is:
cd('/SecurityConfiguration/usar_domain/Realms/myrealm/AuthenticationProviders/DefaultAuthenticator')
cmo.setUserAttributeValue('itar_admin','displayname','Itar')
cmo.setUserAttributeValue('itar_admin','givenname','Admin')
cmo.setUserAttributeValue('itar_admin','mail','itar_admin@some.com')

Is there a way to achieve the above from the domain model ?
