### ISSUE TITLE
Logging properties with asterisk fail to parse

### ISSUE THREAD

**Issue by ddsharpe** [oracle/weblogic-deploy-tooling#562]
```
managed-server-1:
    Log:
        LoggerSeverityProperties:
                    'my.package.*': Debug
```
Will give the following error:
```
<SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018>
```
