### ISSUE TITLE
updateDomain errors on existing security configuration

### ISSUE THREAD

**Issue by gthomas01** [oracle/weblogic-deploy-tooling#617]
When doing an on-line updateDomain.sh I'm getting error when the existing security providers are deleted and recreated.  Even when there is no changes to the configuration.
(In fact fails on update without any changes to the yaml I created the domain with).

Message:

####<Apr 28, 2020 11:02:02 AM> <INFO> <Creator> <_create_mbean> <WLSDPLY-20013> <Updating SecurityConfiguration>
####<Apr 28, 2020 11:02:03 AM> <INFO> <SecurityProviderCreator> <_delete_existing_providers> <WLSDPLY-12135> <Removing Security provider DefaultAuthenticator with Provider type AuthenticationProviders at location /SecurityConfiguration/my_dom/Realms/myrealm>
####<Apr 28, 2020 11:02:03 AM> <INFO> <SecurityProviderCreator> <_delete_existing_providers> <WLSDPLY-12135> <Removing Security provider DefaultIdentityAsserter with Provider type AuthenticationProviders at location /SecurityConfiguration/my_dom/Realms/myrealm>
####<Apr 28, 2020 11:02:03 AM> <INFO> <SecurityProviderCreator> <_delete_existing_providers> <WLSDPLY-12135> <Removing Security provider EHI_AD with Provider type AuthenticationProviders at location /SecurityConfiguration/my_dom/Realms/myrealm>
####<Apr 28, 2020 11:02:03 AM> <INFO> <SecurityProviderCreator> <_create_named_subtype_mbeans> <WLSDPLY-12118> <Creating AuthenticationProvider of type ActiveDirectoryAuthenticator with name EHI_AD at location /SecurityConfiguration/my_dom/Realms/myrealm>
####<Apr 28, 2020 11:02:04 AM> <SEVERE> <update> <main> <WLSDPLY-09015> <updateDomain deployment failed: Failed to set attribute UserBaseDn in path /SecurityConfiguration/my_dom/Realms/myrealm/AuthenticationProviders/EHI_AD to value OU=A0098,OU=Corporate,DC=mydomain,DC=com: Error occurred while performing set : Error setting attribute UserBaseDn : Security:Name=myrealmEHI_AD:UserBaseDn
Use dumpStack() to view the full stacktrace :>

Issue Log for updateDomain version 1.8.0 running WebLogic version 12.2.1.4.0 online mode:

SEVERE Messages:

        1. WLSDPLY-09015: updateDomain deployment failed: Failed to set attribute UserBaseDn in path /SecurityConfiguration/my_dom/Realms/myrealm/AuthenticationProviders/EHI_AD to value OU=A0098,OU=Corporate,DC=mydomain,DC=com: Error occurred while performing set : Error setting attribute UserBaseDn : Security:Name=myrealmEHI_AD:UserBaseDn
Use dumpStack() to view the full stacktrace :

Total:       WARNING :     0    SEVERE :     1

updateDomain.sh failed (exit code = 2)

This is an example of the AD config
......
```
        Realm:
            myrealm:
                SecurityDDModel: DDOnly
                Adjudicator:
                    DefaultAdjudicator:
                        DefaultAdjudicator:
                AuthenticationProvider:
                    EHI_AD:
                        ActiveDirectoryAuthenticator:
                            Principal: 'weblogic@mydomain.com'
                            GroupBaseDN: 'OU=Project Groups,OU=Domain Groups,DC=mydomain,DC=com'
                            UserBaseDn: 'OU=A0098,OU=Corporate,DC=mydomain,DC=com'
                            UserFromNameFilter: '(&amp;(SamAccountName=%u)(objectclass=user))'
                            CredentialEncrypted: '@@PROP:SecurityConfig.CredentialEncrypted@@'
                            Port: 636
                            SSLEnabled: true
                            ControlFlag: SUFFICIENT
                            UserNameAttribute: SamAccountName
                            Host: mydomain.com
                    DefaultAuthenticator:
```
.....
