### ISSUE TITLE
DB2Driver does not accept URL with quotes, but YAML parser requires

### ISSUE THREAD

**Issue by peasoupio** [oracle/weblogic-deploy-tooling#630]
Hi,

I'm trying to create a JDBC resource using a Db2 (Unix) Driver, but I am getting this error:
`weblogic.common.resourcepool.ResourceSystemException: The driver com.ibm.db2.jcc.DB2Driver does not accept URL 'jdbc:db2://SOMETHING'`

Here's the matching part in the YAML file: 
```
JDBCDriverParams:
          DriverName: com.ibm.db2.jcc.DB2Driver
          URL: 'jdbc:db2://SOMETHING'
```

It seems the Db2Driver requires an URL without quotes (or even double-quotes).
Thou, the YAML parser requires some since I get this error without ones:
`domainModel.yml at line 48 position 19: mismatched input ':' expecting {COMMENT, NEWLINE}>`

Am I missing something or is there a legit "bug"?

The WebLogic Deploy Tooling updateDomain version is 1.8.1:master.91c7545

Thank you :)

**Comment by peasoupio** [comment]
I have managed to overcome the issue by using a variable-file. 
Per example: 
domainModel.yml:
```
    URL: @@PROP:my.super.duper.variable@@
```
domainVariables.properties:
```
my.super.duper.variable=jdbc:db2://SOMETHING
```
(For normal readers, take a look at the repo README.md/home page, at the "Model Tokens" section).

I do still believe there should be a special token for URLs. What do you guys think?

**Comment by ddsharpe** [comment]
The quotes are required in the YAML because the YAML parser treats the colon as a special character if it is not in quotes.  But, I would have expected the quotes to have been removed from the value.  We will need to investigate.

@peasoupio What do you mean by "special token" for URLs?

**Comment by peasoupio** [comment]
Thanks for the reply, 

I've read somewhere deploy-tooling used its own YAML parser.
In that way, if it's not possible to fix the output as you said since URL are expected to have colons, maybe a token like `@@URL:my://url:with:colon@@` would allow the parser to recognize when to seek for colons after the key definition (default behavior) and not.
It is more like a "Plan B" than anything else.

**Comment by rakillen** [comment]
I tried a updateDomain (offline and online) using the model section above with `URL: 'jdbc:db2://SOMETHING'`, and it looks like the quotes were removed correctly. My config/jdbc/*-jdbc.xml file had the following:
```
  <jdbc-driver-params>
    <url>jdbc:db2://SOMETHING</url>
    <driver-name>com.ibm.db2.jcc.DB2Driver</driver-name>
  </jdbc-driver-params>
```
What does your config file show when the model has `URL: 'jdbc:db2://SOMETHING'`?
I thought maybe the single-quote characters were off, but it looks correct in your model content and the error message.
Another option would be to try double quotes.
Can you post the full JDBCSystemResource model section, with any sensitive information removed?

**Comment by peasoupio** [comment]
Hi @rakillen,

The URL contains colons, slashes, periods, and letters. No special characters. 
Take a look (formatted): jdbc:db2://aaa##.aaa.aaa:###/aaa

Here is my formatted domain model:
```
domainInfo:
  AdminUserName: defaultUsername
  AdminPassword: defaultPassword
topology:
  AdminServerName: AdminServer
  Server:
    AdminServer:
      ListenPort: 1234
      SSL:
        ListenPort: 12345
        Enabled: true
appDeployments:
  Library:
    mylibrary1.2.3.4:
      SourcePath: '@@DOMAIN_HOME@@/applications/myApp/javaFiles'
      Target: AdminServer
      ModuleType: war
  Application:
    myOtherApp:
      SourcePath: '@@DOMAIN_HOME@@/applications/myOtherApp/javaFiles'
      PlanPath: '@@DOMAIN_HOME@@/applications/myOtherApp/plan.xml'
      Target: AdminServer
      ModuleType: ear
      StagingMode: nostage
      PlanStagingMode: nostage
      SecurityDDModel: Advanced
resources:
  JDBCSystemResource:
    MYJDBC:
      Target: AdminServer
      JdbcResource:
        JDBCDataSourceParams:
          JNDIName: MyJNDIName
        JDBCDriverParams:
          DriverName: com.ibm.db2.jcc.DB2Driver
          URL: 'jdbc:db2://SOMETHING'
          Properties:
            user:
              Value: myuser
            password:
              Value: mypassword
            currentSchema:
              Value: myschema
```

I can't manage right now to show you the generated jdbc.xml file (other reasons). I'll try later.

[EDIT]
While reading, I saw `DriverName`'s value is not between quotes. I'll try using quotes for it.

Thanks again.
