### ISSUE TITLE
discoverDomain.sh does not create archive or model with absolute paths

### ISSUE THREAD

**Issue by roeq** [oracle/weblogic-deploy-tooling#643]
Using discover domain 1.9.0

discoverDomain.sh find the application but doesn't capture the correct path in the model or archive

####<Jun 3, 2020 10:06:17 AM> <INFO> <DeploymentsDiscoverer> <get_applications> <WLSDPLY-06392> <Adding Application new#v1.4>
####<Jun 3, 2020 10:06:17 AM> <INFO> <DeploymentsDiscoverer> <add_application_to_archive> <WLSDPLY-06394> <Add application new#v1.4 binary /apps/new to archive>
```
model:
appDeployments:
    Application:
        'new#v1.4':
            SourcePath: wlsdeploy/applications/new/
            ModuleType: war
            Target: 'blue,green'
```
archive:

[weblogic-deploy-tool]$   jar tvf /tmp/archive.zip 
   252 Wed Jun 03 10:06:16 EDT 2020 wlsdeploy/applications/new/simple.html
   103 Wed Jun 03 10:06:16 EDT 2020 wlsdeploy/applications/new/META-INF/MANIFEST.MF
   376 Wed Jun 03 10:06:16 EDT 2020 wlsdeploy/applications/new/META-INF/.WL_internal/cache/simple/.classinfos/.cache.ser
   376 Wed Jun 03 10:06:16 EDT 2020 wlsdeploy/applications/new/META-INF/.WL_internal/cache/new/.classinfos/.cache.ser
   366 Wed Jun 03 10:06:16 EDT 2020 wlsdeploy/applications/new/WEB-INF/web.xml
   165 Wed Jun 03 10:06:16 EDT 2020 wlsdeploy/applications/new/WEB-INF/weblogic.xml
