### ISSUE TITLE
JNDI in data source is incorrect

### ISSUE THREAD

**Issue by jonipaananen** [oracle/weblogic-deploy-tooling#660]
This is identical to https://github.com/oracle/weblogic-deploy-tooling/issues/255, but that issue was closed due to the reporter not responding

I'm using WL 12.2.1.4.0, WDT 1.9.0

This is an excerpt from the yaml:
```
resources:
   JDBCSystemResource:
      'dsname':
         Target: 'Server-Cluster'
         DescriptorFileName: 'jdbc/dsname-jdbc.xml'
         JdbcResource:
            JDBCConnectionPoolParams:
               TestTableName: SQL SELECT getdate()
            JDBCDataSourceParams:
               GlobalTransactionsProtocol: EmulateTwoPhaseCommit
               JNDIName: jdbc/dsname
            JDBCDriverParams:
               URL: '@@PROP:db.server.url@@'
               PasswordEncrypted: '@@PROP:user.r.password@@'
               DriverName: com.microsoft.sqlserver.jdbc.SQLServerDataSource
               Properties:
                  user:
                     Value: '@@PROP:user.r@@'
                  databaseName:
                     Value: '@@PROP:database@@'
```

This works when setting up a net new domain, but when using updateDomain.cmd to add a new data source, the JNDI name is incorrect. In the example above, when looking in the console after running updateDomain.cmd, the jndi would be:
```
dsname
jdbc/dsname
```

The expected value would be:

```
jdbc/dsname
```

In addition, if a jndi name is changed, the old value is not removed, but the new one is added. For example, if the original jndi name is `jdbc/dsname` and it's changed to `jdbc/dsname2` in the yaml, the resulting value in the console is:
```
jdbc/dsname
jdbc/dsname2
```

edit: I forgot to mention, I'm running updateDomain in online mode.
