### ISSUE TITLE
Issue whit generation of model.yaml and binding.yaml

### ISSUE THREAD

**Issue by antonionappi88** [oracle/weblogic-deploy-tooling#760]
Hello,
I'm following this guide: https://github.com/verrazzano/examples/blob/master/todo-list/README.md but using a real domain that we have in production.

I got to the end and I was going to deploy to Kubernetes the `model.yaml` and `binding.yaml`

With my surprise if failed with:

```bash
The VerrazzanoModel "base_domain-model" is invalid: metadata.name: Invalid value: "base_domain-model": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

This because the name of my domain contains the `_`(`base_domain`) and the YAML contains:

```
apiVersion: verrazzano.io/v1beta1
kind: VerrazzanoModel
metadata:
  name: base_domain-model
  namespace: default
```

Maybe the validity of two YAMLs could be checked earlier in the WDT.

Cheers,
Antonio
