### ISSUE TITLE
storageXMLLocation error

### ISSUE THREAD

**Issue by dborysenko** [oracle/weblogic-deploy-tooling#767]
Hello Team,
We were trying to utilize storageXMLLocation option in our WDT model to switch SOA tablespace big file option to true. Looks like the option is bugged.
Steps to reproduce:

1. Add Storage.xml to your archive file under wlsdeploy/rcu/config/Storage.xml
2. Refer custom storage config in your model file: 
```
domainInfo:
  AdminUserName: '@@FILE:/weblogic-operator/secrets/username@@'
  AdminPassword: '@@FILE:/weblogic-operator/secrets/password@@'
  ServerStartMode: prod
  RCUDbInfo:
    rcu_prefix: '@@PROP:rcuSchemaPrefix@@'
    rcu_schema_password: '@@PROP:rcuSchemaPassword@@'
    rcu_db_user: '@@PROP:rcuAdminUser@@'
    rcu_admin_password: '@@PROP:rcuAdminPassword@@'
    rcu_db_conn_string: '@@PROP:rcuDatabaseURL@@'
    rcu_variables: "SOA_PROFILE_TYPE=LARGE,HEALTHCARE_INTEGRATION=NO"
    storageXMLLocation: 'wlsdeploy/rcu/config/Storage.xml'
  ServerGroupTargetingLimits:
[skipped]
```
3. Kick domain creation job.
4. Log file /shared/wdt/createDomain.sh.out contains below output
```
[root@as-k8sdv-msdc01 ~]# tail -f /shared/wdt/createDomain.sh.out 
JDK version is 1.8.0_271-b09
JAVA_HOME = /u01/jdk
WLST_EXT_CLASSPATH = /shared/wdt/weblogic-deploy/lib/weblogic-deploy-core.jar
CLASSPATH = /shared/wdt/weblogic-deploy/lib/weblogic-deploy-core.jar
WLST_PROPERTIES = -Dcom.oracle.cie.script.throwException=true -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployCustomizeLoggingConfig 
/u01/oracle/oracle_common/common/bin/wlst.sh /shared/wdt/weblogic-deploy/lib/python/create.py -oracle_home /u01/oracle -domain_type OSB -domain_home /shared/domains/as-domain3 -model_file /shared/wdt/wdt_model.yaml,/shared/wdt/wdt_osb_cluster.yaml,/shared/wdt/wdt_web_cluster1.yaml,/shared/wdt/wdt_web_cluster2.yaml,/shared/wdt/wdt_web_cluster3.yaml -variable_file /shared/wdt/create-domain-inputs.yaml -archive_file /shared/wdt/wlsdeploy.zip -use_encryption -run_rcu

Initializing WebLogic Scripting Tool (WLST) ...

Jython scans all the jar files it can find at first startup. Depending on the system, this process may take a few minutes to complete, and WLST may not return a prompt right away.

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

####<Oct 26, 2020 6:23:43 PM> <INFO> <WebLogicDeployToolingVersion> <logVersionInfo> <WLSDPLY-01750> <The WebLogic Deploy Tooling createDomain version is 1.9.6:master.2c18938:Oct 19, 2020 21:56 UTC>
Enter the encryption passphrase used to encrypt the model passwords: ####<Oct 26, 2020 6:23:47 PM> <WARNING> <WLSRoles> <_process_roles_map> <WLSDPLY-12502> <The role IntegrationAdmin is not a WebLogic global role and will use the expression as specified>
####<Oct 26, 2020 6:23:55 PM> <INFO> <filter_helper> <apply_filters> <WLSDPLY-20017> <No filter configuration file /shared/wdt/weblogic-deploy/lib/model_filters.json>
####<Oct 26, 2020 6:23:55 PM> <INFO> <filter_helper> <apply_filters> <WLSDPLY-20016> <No filters of type create found in filter configuration file /shared/wdt/weblogic-deploy/lib/model_filters.json>
####<Oct 26, 2020 6:23:55 PM> <SEVERE> <create> <main> <WLSDPLY-12409> <createDomain failed to create the domain: Unable to extract wlsdeploy/rcu/config/Storage.xml from archive file /shared/wdt/wlsdeploy.zip: WLSDeployArchive /shared/wdt/wlsdeploy.zip unable to add/extract binaries because the directory /shared/domains/as-domain3 does not exist>

Issue Log for createDomain version 1.9.6 running WebLogic version 12.2.1.4.0 offline mode:

WARNING Messages:

        1. WLSDPLY-12502: The role IntegrationAdmin is not a WebLogic global role and will use the expression as specified

SEVERE Messages:

        1. WLSDPLY-12409: createDomain failed to create the domain: Unable to extract wlsdeploy/rcu/config/Storage.xml from archive file /shared/wdt/wlsdeploy.zip: WLSDeployArchive /shared/wdt/wlsdeploy.zip unable to add/extract binaries because the directory /shared/domains/as-domain3 does not exist

Total:       WARNING :     1    SEVERE :     1

createDomain.sh failed (exit code = 2)
```

Looks like WDT tries to extract Storage.xml file before DOMAIN_HOME_DIR (/shared/domains/as-domain3 in my example) directory got created.
Let me know if further details are needed to fix it.

PS: I think IntegrationAdmin warning can be ignored. It is not related to the question.
