### ISSUE TITLE
storageXMLLocation wrong argument order

### ISSUE THREAD

**Issue by dborysenko** [oracle/weblogic-deploy-tooling#779]
Hi Team,
Enabling storageXMLLocation option in model file results into wrong argument order for subsequent rcu command.

example snippet from model file:
```
domainInfo:
  AdminUserName: '@@FILE:/weblogic-operator/secrets/username@@'
  AdminPassword: '@@FILE:/weblogic-operator/secrets/password@@'
  ServerStartMode: prod
  RCUDbInfo:
    rcu_prefix: prefix1
    rcu_schema_password: passwd
    rcu_db_user: sys
    rcu_admin_password: qwerty
    rcu_db_conn_string: mydb.example.com:1521/mysid
    rcu_variables: "SOA_PROFILE_TYPE=LARGE,HEALTHCARE_INTEGRATION=NO"
    storageXMLLocation: 'wlsdeploy/rcu/config/Storage.xml'
[skipped]
```

Above model file results into below rcu run:
```
####<Nov 9, 2020 8:21:40 PM> <INFO> <ScriptRunner> <executeScript> <WLSDPLY-01300> <Executing rcu: [cmd:[/usr/bin/sh, -c, /u01/oracle/oracle_common/bin/rcu -silent -createRepository -databaseType ORACLE -useSamePasswordForAllSchemaUsers true -connectString mydb.example.com:1521/mysid -dbUser sys -dbRole SYSDBA -schemaPrefix prefix1 -component STB -component WLS -component MDS -component IAU -component IAU_VIEWER -component IAU_APPEND -component OPSS -component UCSUMS -component SOAINFRA -storageXMLLocation /shared/domains/domain1/wlsdeploy/rcu/config/Storage.xml -variables SOA_PROFILE_TYPE=LARGE,HEALTHCARE_INTEGRATION=NO -f]]>
```

As you can see "storageXMLLocation" argument is next to last one. It is a problem. RCU requires strict argument order, other wise one can get unpredicted behavior. In our case RCU simply ignores storageXMLLocation argument.
From Doc ID 2021896.1, correct argument order should be something like:

```
rcu [-silent | -interactive] -createRepository
   [-compInfoXMLLocation omponentInfo.xml_file_location]
   [-storageXMLLocation Storage.xml_file_location]
   [-databaseType [ORACLE|EBR]]
   -connectString database_connect_string
   [-edition edition_name]
   -dbUser database_username
   [-dbRole database_user_role]
   [-unicodeSupport [Yes|No]]
   [-skipCleanupOnFailure [Yes|No]]
   [-useSamePasswordForAllSchemaUsers [true|false]]
   [-selectDependentsForComponents [true|false]]
   [-variables variablename=value]
   [-schemaPrefix schema_prefix]
   -component component_ID
   -tablespace component_tablespace_name
   -tempTablespace component_temp_tablespace_name
```

In my case, i went ahead and tried to run rcu manually with below argument order:
```
/u01/oracle/oracle_common/bin/rcu -silent -createRepository -compInfoXMLLocation /u01/oracle/oracle_common/rcu/config/ComponentInfo.xml -storageXMLLocation /shared/domains/domain1/wlsdeploy/rcu/config/Storage.xml -databaseType ORACLE -useSamePasswordForAllSchemaUsers true -connectString mydb.example.com:1521/mysid -dbUser sys -dbRole SYSDBA -schemaPrefix prefix1 -component STB -component WLS -component MDS -component IAU -component IAU_VIEWER -component IAU_APPEND -component OPSS -component UCSUMS -component SOAINFRA -variables SOA_PROFILE_TYPE=LARGE,HEALTHCARE_INTEGRATION=NO
```
Above command did pick up my custom Storage.xml file. The ask is to fix RCU argument order.

PS:
If the one wants to specify storageXMLLocation argument he must set compInfoXMLLocation as well, otherwise you'll get error like below:
```
ERROR - RCU-6302 Command line arguments validation failed.
CAUSE - RCU-6302 Value for "-compInfoXMLLocation" was not provided. 
ACTION - RCU-6302 Provide values for both "-compInfoXMLLocation" and "-storageXMLLocation" or invoke without any of these arguments.
```
