### ISSUE TITLE
discoverDomain is missing JMS resource details

### ISSUE THREAD

**Issue by zeusbaba** [oracle/weblogic-deploy-tooling#792]
I did export WDT template using `discoverDomain`, from `12.1.3.0.0`, it worked without issues.  
However, after analysing the template, I noticed that the details of JMS resource was missing.  

the original resource file contains  
```
<foreign-server name="UMSAQJMSForeignServer">
    <default-targeting-enabled>true</default-targeting-enabled>
    <foreign-destination name="OraSDPM/Queues/OraSDPMAppDefRcvQ1">
      <local-jndi-name>OraSDPM/Queues/OraSDPMAppDefRcvQ1</local-jndi-name>
      <remote-jndi-name>Queues/OraSDPMAppDefRcvQ1</remote-jndi-name>
    </foreign-destination>
    ...

```  

but the exported WDT template is missing `foreign-destination / ForeignDestination` details  
```
ForeignDestination:
    OraSDPM/Queues/OraSDPMAppDefRcvQ1:
    OraSDPM/Queues/OraSDPMAppDefRcvErrorQ1:
    ...
```  
as far as I know, the expected output should be   
```
OraSDPM/Queues/OraSDPMAppDefRcvQ1:
    LocalJNDIName: OraSDPM/Queues/OraSDPMAppDefRcvQ1
    RemoteJndiName: Queues/OraSDPMAppDefRcvQ1
...
```
