### ISSUE TITLE
WDT fails to set DestinationKeys property value

### ISSUE THREAD

**Issue by tomvit** [oracle/weblogic-deploy-tooling#805]
When setting the WLS JMS destination key, there is an issue to assign the destination key using WDT (confirmed with WDT versions 1.8.0 and 1.9.7). 

In order to reproduce the error, the below model is not working: 

```
resources:
  JMSSystemResource:
       AIAJMSModule:
            JmsResource:
                UniformDistributedQueue:
                    AIA_CRTBO_OUT_JMSQ:
                        DestinationKey: "AIA_SALESORDERJMSPRIORITY_KEY"
                    AIA_CRTCUST_OUT_JMSQ:
                        DestinationKey: "AIA_SALESORDERJMSPRIORITY_KEY"
                    AIA_CRTFO_OUT_JMSQ:
                        DestinationKey: "AIA_SALESORDERJMSPRIORITY_KEY"
                    AIA_FOPROV_OUT_JMSQ:
                        DestinationKey: "AIA_SALESORDERJMSPRIORITY_KEY"
```

And the error is as follows (WDT 1.9.7):

```
Issue Log for updateDomain version 1.9.7 running WebLogic version 12.2.1.4.0 online mode:

SEVERE Messages:

        1. WLSDPLY-09015: updateDomain deployment failed: Failed to set attribute DestinationKeys in path /JMSSystemResources/AIAJMSModule/JMSResource/AIAJMSModule/UniformDistributedQueues/AIA_CRTCUST_OUT_JMSQ to value AIA_SALESORDERJMSPRIORITY_KEY: Error occurred while performing set : Error setting attribute DestinationKeys : java.lang.ClassCastException@3ecf9cdd
Use dumpStack() to view the full stacktrace :

Total:       WARNING :     0    SEVERE :     1
```

We have analyzed the issue and discovered that the method `set` in `wlst_helper.py` is as follows:

```
self.__load_global('set')(attribute, value)
```

where `value` is a string but for `DestinationKeys` it should be as follows:

```
self.__load_global('set')(attribute,jarray.array([String(value)], String))
``` 

We created a "hotfix" in `wlst_helper.py` for our own purpose as this was a blocker in our project but obviously the root cause is likely somewhere else in the code. It would be good if we can get this fixed. 

```
# hotfix for error to set DesintationKeys
if attribute == 'DestinationKeys':
  if not isinstance(value, list):
    value = [ x.strip() for x in value.split(',') ]
  value = jarray.array([java.lang.String(x.strip()) for x in value], java.lang.String)
```
