### ISSUE TITLE
WDT adds unexpected sub-deployments to connection factories

### ISSUE THREAD

**Issue by textanalyticsman** [oracle/weblogic-deploy-tooling#825]
Hello,

I have used WDT to discover a SOA/BPM 12.2.1.4 domain and then after building the domain I have found below error when I tried to startup the AdminServer.

> Caused` By: weblogic.descriptor.DescriptorValidateException: The following failures occurred: 
-- [JMSExceptions:045110]The JMS resource named "JmsConnectionFactory-Example" has incorrect targeting information. This resource has the default-targeting-enabled attribute set to true and has a valid sub-deployment-name value specified.`

I have identified the issue in the model as you can see on the below snippet. The issue is that in our original system we do not have this ` SubDeploymentName: 'JmsConnectionFactory-ExampleDistCF'`. However, WDT has added it.

I am using WDT 1.9.8

```
JMSSystemResource:
        ExampleManagerJMSModule:
            SourcePath: './config/jms/ExampleManagerJMSModule-jms.xml'
            Target: BpmCluster
            SubDeployment:
                ExampleManager_cluster:
                    Target: ExampleManagerJMSServer_BPM_01
            JmsResource:
                ConnectionFactory:
                    'JmsConnectionFactory-ExampleDistCF':
                        SubDeploymentName: 'JmsConnectionFactory-ExampleDistCF'
                        JNDIName: jms/example/ExampleDistCF
                        DefaultTargetingEnabled: true
                    'JmsConnectionFactory-ExampleNowCF':
                        SubDeploymentName: 'JmsConnectionFactory-ExampleNowCF'
                        JNDIName: jms/example/ExampleNowCF
                        DefaultTargetingEnabled: true
                        ClientParams:
                            ClientIdPolicy: Unrestricted
                        TransactionParams:
                            XAConnectionFactoryEnabled: true
```

Best regards,
TAM

**Comment by textanalyticsman** [comment]
The same issue with foreign servers.

WDT 1.9.8 has added a `SubDeploymentName: EXAMPLE_FS` element that we do not have on the source system used to extract the model. This in combination with `DefaultTargetingEnabled:true` does not allow the AdminServer to start.

```
                ForeignServer:
                    EXAMPLE_FS:
                        DefaultTargetingEnabled: true
                        ConnectionURL: '@@PROP:JMS.EXAMPLEJMSModule.EXAMPLE_FS.ConnectionURL@@'
                        SubDeploymentName: EXAMPLE_FS
```
