### ISSUE TITLE
setting `RotateLogOnStartup: true` attribute doesnot have any effect

### ISSUE THREAD

**Issue by zeusbaba** [oracle/weblogic-deploy-tooling#879]
When configuring OSB domain, I would like to customise `Log:` attribute with extended params.  
One of those params doesnot have any effect, aka it doesnot set the server's logging config.  

See   
```
Log:
        FileCount: 20
        LogFileRotationDir: /u06/{{ oracle_user }}/logs/rotatedLogs
        RotateLogOnStartup: true
        RotationType: bySize
        NumberOfFilesLimited: true
        RedirectStderrToServerLogEnabled: true
        RedirectStdoutToServerLogEnabled: true
        FileMinSize: 5000
        DomainLogBroadcasterBufferSize: 1
        FileName: {{ domain_logs_dir }}.log
```   
When check AdminServer console, I see that all attributes are actively set, except `RotateLogOnStartup: true`  which does no effect on the server's Log configuration, aka `Rotate log file on startup` is still inactive.    

- WDT version: `20210402 built from master branch`  
- OSB version: `12.2.1.4`  

Can you please advise/help?
