### ISSUE TITLE
user created using model can not authenticate

### ISSUE THREAD

**Issue by rjnkmr** [oracle/weblogic-deploy-tooling#917]
I am creating a user with Administrators Group
```
topology:
  Security:
    User:
      testuser:
          Password: MyPwd1234
          GroupMemberOf: Administrators
```
but i can not login to weblogic console using this user "testuser" and get " Authentication Denied" message.
After logging in with another Administrators user to weblogic console, i can see that "testuser" exists and has got Administrators Group (under: Security Realms -> myrealm -> Users and Groups -> testuser -> ..)

By creating the same User, Password and Group combination in weblogic console directly, it works  and i can log in to console with this user.

This problem is since release-1.9.14. In earlier versions it worked.
