### ISSUE TITLE
Update Domain Tool: can not deploy with SourcePath as relative path in WLST online mode

### ISSUE THREAD

**Issue by rjnkmr** [oracle/weblogic-deploy-tooling#931]
I am using the Create Domain Tool to create the domain (WLST offline) and Update Domain Tool (WLST online) to  update the domain (and also for appDeployments update)
In both the cases without "archive_file" option (as I am copying the war or ear files to the necessary location myself).

I have noticed that createDomain.sh (WLST offline) works but updateDomain.sh (WLST online) does not.
e.g. with 

```
appDeployments:
  Application:
    testapp:
      SourcePath: "pf-appl/dist/test.war"
      Target: "CLUWDT"
```

after runnging updateDomain (WLST online,  without "archive_file" option), I get this error

SEVERE Messages:

        1. WLSDPLY-09015: updateDomain deployment failed: Failed to get hash for file pf-appl/dist/test.war because the entry did not point into the archive and was not an absolute path

although "pf-appl/dist/test.war" exists (relative to the domain directory).
With absolute path it works.

With "archive_file" option also it works if "SourcePath" is subdirectory of wlsdeploy

e.g.

```
appDeployments:
  Application:
    testapp:
      SourcePath: "wlsdeploy/applications/test.war"
      Target: "CLUWDT"
```
