### ISSUE TITLE
Update Domain Tool (WLST online mode) can not update appDeployment by updating the SourcePath file

### ISSUE THREAD

**Issue by rjnkmr** [oracle/weblogic-deploy-tooling#932]
I want to update an appDeployment by updating the war file and running the Update Domain Tool (WLST online mode) 
e.g.
Deploy an application "test.war" using Create or Update Domain Tool and then modify test.war and deploy again using Update Domain Tool
Model is:
```
appDeployments:
  Application:
    testapp:
      SourcePath: "/mypath/pf-appl/dist/test.war"
      Target: "CLUWDT"

```
With Create or Update Domain Tool, I have deployed the application first time and now I want to modify it by changing the "/mypath/pf-appl/dist/test.war" file and running Update Domain Tool (WLST online)
but I get this message:
`####<Jun 30, 2021 3:15:57 PM> <INFO> <ApplicationDeployer> <remove_app_from_deployment> <WLSDPLY-09311> <testapp has already been deployed, it will not be redeployed since the binary file has not changed>
`

although the test.war has changed and that means the  binary file has changed.

It works if the file name changes  e.g. `SourcePath: "/mypath/pf-appl/dist/test2.war"`, so by updating with model and changing the war file name

```
appDeployments:
  Application:
    testapp:
      SourcePath: "/mypath/pf-appl/dist/test2.war"
      Target: "CLUWDT"
```
