### ISSUE TITLE
Update Domain Tool (WLST online mode): some of the attributes are ignored

### ISSUE THREAD

**Issue by rjnkmr** [oracle/weblogic-deploy-tooling#933]
I am deploying (appDeployment) using Update Domain Tool (WLST online mode) and i noticed that some of the attributes are ignored and have no effect.
for example, the attributes : StagingMode, Notes 

```
appDeployments:
  Application:
    testapp:
      SourcePath: "/mypath/pf-appl/dist/test.war"
      Target: "CLUWDT"
      StagingMode: nostage
      Notes: "my notes about test war"
```

With Create Domain Tool (WLST offline), it works.

Wtih Model Help Tool, I see these attributes for appDeployment are possible:
```
appDeployments:
    Application:
        'App-1':
            AltDescriptorDir:        # string
            AltDescriptorPath:       # string
            AltWLSDescriptorPath:    # string
            ApplicationIdentifier:   # string
            ApplicationName:         # string
            CacheInAppDirectory:     # boolean
            CompatibilityName:       # string
            DeploymentOrder:         # integer
            DeploymentPrincipalName: # string
            InstallDir:              # string
            ModuleType:              # string
            Notes:                   # string
            ParallelDeployModules:   # boolean
            PlanDir:                 # string
            PlanPath:                # string
            PlanStagingMode:         # string
            SecurityDDModel:         # string
            SourcePath:              # string
            StagingMode:             # string
            Target:                  # delimited_string
            Untargeted:              # boolean
            ValidateDDSecurityData:  # boolean
            VersionIdentifier:       # string

```
