### ISSUE TITLE
Online discoverDomain.sh does not extract workmanagers for SOA properly

### ISSUE THREAD

**Issue by textanalyticsman** [oracle/weblogic-deploy-tooling#939]
Hello,

When discoverDomain.sh online is executed I get this.

```
            DigitalizationWMG_dspEngine:
                Target: BpmCluster
```

However, if I use the offline mode I get this.

```
            DigitalizationWMG_dspEngine:
                MinThreadsConstraint: DigitalizationWMG_dspEngine_minThreads_1
                MaxThreadsConstraint: SOAInternalProcessing_maxThreads
                FairShareRequestClass: soa_fairShare_80
                Target: BpmCluster
```

Is it possible to fix the online mode to get the same information?

Best regards,
TAM
