### ISSUE TITLE
How to specify an in-EAR JMS subdeployment

### ISSUE THREAD

**Issue by sschober** [oracle/weblogic-deploy-tooling#951]
We currently deploy a JMS configuration in our EAR file, using a subdeployment.

This leads to the following `config.xml` in weblogic domain:

```xml
<app-deployment>
    <name>my-app</name>
    <target>ManagedServer</target>
    <module-type>ear</module-type>
    <source-path>servers/AdminServer/upload/my-app/app/my-app-2.1.0-SNAPSHOT.ear</source-path>
    <sub-deployment>
      <name>my-app-jms</name>
      <sub-deployment>
        <name>my-app</name>
        <target>JMSServer-My-App</target>
      </sub-deployment>
    </sub-deployment>
...
  </app-deployment>
```

To reproduce this with WDT, we tried specifying a `SubDeployment` child node in the `domain.yaml`, like so, but failed expectedly:

```yaml
appDeployments:
    Application:
        # Quote needed because of hyphen in string
        '@@PROP:ApplicationName@@':
            SourcePath: 'wlsdeploy/applications/@@PROP:ApplicationFile@@'
            ModuleType: ear
            Target: 'ManagedServer'
            StagingMode: nostage
            PlanStagingMode: nostage
            SubDeployment:
                'my-app-jms':
                    SubDeployment:
                        'my-app':
                            Target: 'JMSServer-My-App'
```

WDT log result:
```
...
#13 26.53         2. WLSDPLY-05026: SubDeployment is not one of the folder names allowed in model location appDeployments:/Application/my-app
...
```

Is it all possible to specify a in EAR-subdeployment JMS configuration in a domain.yaml file with WDT?
