### ISSUE TITLE
Cannot define 'SingleSignOnServices' element for WLS 12.1.3 domain

### ISSUE THREAD

**Issue by lukasged** [oracle/weblogic-deploy-tooling#97]
I'm running the weblogic deploy tooling version `0.10`, with an installation of WebLogic Server version `12.1.3` and JDK version `1.8.0_162-b12`.

I'm trying to create a domain using the `createDomain` tool and a model which defines the `SingleSignOnServices` element for managed server (topology->Server) entries. The model that I'm using is the following:
```yaml
domainInfo:
  AdminPassword: weblogic123
  AdminUserName: weblogic
  ServerStartMode: prod
topology:
  AdminServerName: AdminServer
  Cluster:
    cluster1:
      ClusterMessagingMode: unicast
      DynamicServers:
        MaximumDynamicServerCount: 0
  Name: base_domain
  Server:
    AdminServer:
      ListenAddress: ''
      ListenPort: '8001'
      Log:
        FileName: /logs/AdminServer.log
        NumberOfFilesLimited: true
        RotateLogOnStartup: false
        RotationType: none
    wlsmanaged1:
      Cluster: cluster1
      ListenAddress: wlsmanaged1
      ListenPort: '10110'
      Log:
        FileName: /logs/wlsmanaged1.log
        NumberOfFilesLimited: true
        RotateLogOnStartup: false
        RotationType: none
      SingleSignOnServices:
        WantArtifactRequestsSigned: true
```

When I run the `createDomain` tool and provide this model, it gives me the following error:
```sh
$ /ORA/dbs01/oracle/product/Middleware/weblogic-deploy-tooling/weblogic-deploy/bin/createDomain.sh \
    -oracle_home /ORA/dbs01/oracle/product/Middleware \
    -domain_type WLS \
    -domain_parent /ORA/dbs01/oracle/product/Middleware/user_projects/domains \
    -model_file /ORA/dbs01/oracle/product/Middleware/generated_wls_model.yml
JDK version is 1.8.0_162-b12
JAVA_HOME = /ORA/dbs01/oracle/product/jdk8
WLST_EXT_CLASSPATH =
CLASSPATH = /ORA/dbs01/oracle/product/Middleware/weblogic-deploy-tooling/weblogic-deploy/lib/weblogic-deploy-core.jar
WLST_PROPERTIES = -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployLoggingConfig -Dcom.oracle.cie.script.throwException=true
/ORA/dbs01/oracle/product/Middleware/wlserver/common/bin/wlst.sh /ORA/dbs01/oracle/product/Middleware/weblogic-deploy-tooling/weblogic-deploy/lib/python/create.py -oracle_home /ORA/dbs01/oracle/product/Middleware -domain_type WLS -domain_parent /ORA/dbs01/oracle/product/Middleware/user_projects/domains -model_file /ORA/dbs01/oracle/product/Middleware/generated_wls_model.yml
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
The createDomain program will write its log to /ORA/dbs01/oracle/product/Middleware/weblogic-deploy-tooling/weblogic-deploy/logs/createDomain.log

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

####<May 8, 2018 12:38:07 PM> <INFO> <Validator> <__validate_model_file> <WLSDPLY-05002> <Performing validation in TOOL mode for WebLogic Server version 12.1.3.0.0 and WLST OFFLINE mode>
####<May 8, 2018 12:38:07 PM> <INFO> <Validator> <__validate_model_file> <WLSDPLY-05003> <Performing model validation on the model file /ORA/dbs01/oracle/product/Middleware_12.1.3.0_generic/generated_wls_model.yml>
####<May 8, 2018 12:38:07 PM> <INFO> <Validator> <__validate_domain_info_section> <WLSDPLY-05008> <Validating the domainInfo section of the model file>
####<May 8, 2018 12:38:07 PM> <INFO> <Validator> <__validate_model_section> <WLSDPLY-05008> <Validating the topology section of the model file>
####<May 8, 2018 12:38:08 PM> <SEVERE> <create> <validate_model> <WLSDPLY-20000> <createDomain encountered an unexpected validation error: Failed to get model folder path for location (model_folders = ['Server', 'SingleSignOnServices'],  'name_tokens' = {'SERVER': 'wlsmanaged1'}): Unable to compute the name token for folder /Server/SingleSignOnServices because the folder is not valid in WebLogic Server version 12.1.3.0.0>

createDomain.sh failed (exit code = 2)
```

Is the definition of `SingleSignOnServices` elements supported for weblogic deploy tooling and WLS `12.1.3` ?

Thanks.
