### ISSUE TITLE
OSB target issue

### ISSUE THREAD

**Issue by textanalyticsman** [oracle/weblogic-deploy-tooling#975]
Hello,

After deploying an OSB 12.2.1.4 domain the application `Service Bus WS Transport Provider` is configured with two targets `AdminServer, OsbCluster` and then I tried to fix it by adding below configuration.

```
appDeployments:
    Application:
        Service Bus WS Transport Provider:
            CompatibilityName: 'Service Bus - WS Transport Provider'
            SourcePath: '@@ORACLE_HOME@@/osb/lib/transports/ws-transport.ear'
            ModuleType: ear
            DeploymentOrder: 45
            StagingMode: nostage
            Target: OsbCluster
```
However, after running with previous model the application still has two targets `AdminServer, OsbCluster` rather than just `OsbCluster`.

I am creating the domain by running createDomain.sh and I am using WDT 1.9.17

Best regards,
TAM

**Comment by textanalyticsman** [comment]
I tried to delete the application to deploy it again by using below model.

```
appDeployments:
    Application:
        '!Service Bus WS Transport Provider':
        Service Bus WS Transport Provider:
            CompatibilityName: 'Service Bus - WS Transport Provider'
            SourcePath: '@@ORACLE_HOME@@/osb/lib/transports/ws-transport.ear'
            ModuleType: ear
            DeploymentOrder: 45
            StagingMode: nostage
            Target: OsbCluster
```

However, it failed with this message

```
    SEVERE Messages:

            1. WLSDPLY-12410: createDomain failed to deploy the resources and applications to the domain: cd(/AppDeployment/Service Bus WS Transport Provider) in offline mode failed: No match found for element AppDeployment

```

TAM
