### ISSUE TITLE
Issue createDomain.sh RCU SCAN URL

### ISSUE THREAD

**Issue by textanalyticsman** [oracle/weblogic-deploy-tooling#978]
Hello,

I am trying to create a SOA 12.2.1.4 domain by using the below model, which has a SCAN URL for our database as you can see in the field ```rcu_db_conn_string```

```
domainInfo:
  AdminUserName: weblogic
  AdminPassword: weblogic
# The following group targeting is key to deploy applications on right targets
# https://github.com/oracle/weblogic-deploy-tooling/blob/e42cec7d56649b774e2c7bdb7d96dc2f2fd72137/site/use_cases.md#targeting-server-groups
  ServerGroupTargetingLimits:
    'WSMPM-MAN-SVR': WsmCluster     # Right group for WSM as we use WSM servers and WSM services outside SOA servers
    'OSB-MGD-SVRS-ONLY': OsbCluster # Using this as in this POC WSM are implemented on other cluster
  RCUDbInfo:
    rcu_prefix: "HWORLD"
    rcu_schema_password: "CLAVE"
    rcu_db_conn_string: '(DESCRIPTION=(LOAD_BALANCE=OFF)(FAILOVER=ON)(CONNECT_TIMEOUT=5)(TRANSPORT_CONNECT_TIMEOUT=3000)(RETRY_COUNT=3)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=hello01.domain.com)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=hello02.domain.com)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=dbservice)(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC))))'
```
However, it is failing with the below error

```
####<Sep 15, 2021 1:26:01 PM> <FINER> <DomainCreator> <__apply_base_domain_config> <> <RETURN>
####<Sep 15, 2021 1:26:01 PM> <INFO> <DomainCreator> <__extend_domain_with_select_template> <WLSDPLY-12205> <Writing base domain osbcust-osb-poc01 to directory /u01/weblogic/domains/osb_domain>
####<Sep 15, 2021 1:26:01 PM> <FINER> <WlstHelper> <write_domain> <> <ENTRY /u01/weblogic/domains/osb_domain>
####<Sep 15, 2021 1:26:05 PM> <WARNING> <JpsDataManagerUtil> <getDBConnection> <> +<Can not connect DB with URL jdbc:oracle:thin:@hello01.domain.com:1521:DBSERVICE
java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
```

I think the problem is caused because WDT generates this URL, which is suitable for SID.

```jdbc:oracle:thin:@hello01.domain.com:1521:DBSERVICE```

In our case we need a URL like this, which is suitable for service name

```jdbc:oracle:thin:@hello01.domain.com:1521/DBSERVICE```

If this is an issue, I think the potential cause could be around this source code https://github.com/oracle/weblogic-deploy-tooling/blob/18d05d99a04fbdf97350cd2ab27c6a696418d05f/core/src/main/python/wlsdeploy/tool/create/domain_creator.py#L1083-L1088

Nevertheless, if I am missing a configuration property to use SERVICE rather than SID, kindly let me know.

Best regards,
TAM
