### ISSUE TITLE
WebServerLog/ELFFields not working

### ISSUE THREAD

**Issue by pwninja** [oracle/weblogic-deploy-tooling#983]
I am trying to configure ELFFields in Weblogic domain. using createDomain.sh, but it is not getting reflected.
snippet of topology configuration:
```
            WebServer:
                WebServerLog:
                    FileCount: 25
                    RotateLogOnStartup: true
                    LogFileFormat: extended
                    LogFileRotationDir: '{{ logs_directory }}/AdminServer/backup'
                    ELFFields: "date time cs-method sc-status"
                    DateFormatPattern: 'MMM d, yyyy h:mm:ss,SSS a z'
                    FileName: '{{ logs_directory }}/AdminServer/access_extended.log'
                    LogTimeInGMT: true
```
This is just an example. Actually I need to for the custom fields, but the above one still doesn't work.
Resulting config.xml section is:
```
    <web-server>
      <name>AdminServer</name>
      <web-server-log>
        <name>AdminServer</name>
        <date-format-pattern>MMM d, yyyy h:mm:ss,SSS a z</date-format-pattern>
        <file-name>(...)/AdminServer/access_extended.log</file-name>
        <file-count>25</file-count>
        <log-file-rotation-dir>(...)/AdminServer/backup</log-file-rotation-dir>
        <elf-fields>date time cs-method ctx-ecid ctx-rid cs-uri sc-status bytes</elf-fields>
        <log-file-format>extended</log-file-format>
        <log-time-in-gmt>true</log-time-in-gmt>
      </web-server-log>
```
It always defaults to `date time cs-method ctx-ecid ctx-rid cs-uri sc-status bytes`.
I didn't find any related information in the WDT log file.
Oracle Weblogic version is 12.2.1.4
WDT version is 1.9.17. I also tried 1.9.8 as it was mentioed to be working fine in another ticket (#817), but maybe it works only in the updateDomain.sh scenario.
